language: node_js
node_js:
    - "9"
cache:
    directories:
        - node_modules
script:
    - yarn test --coverage

after_success:
    - cat ./coverage/*.info | ./node_modules/coveralls/bin/coveralls.js
