language: node_js
node_js:
    - "9"
branches:
    only:
        - master
cache:
    directories:
        - node_modules
script:
    - yarn test:ci --coverage

after_success:
    - cat ./coverage/*.info | ./node_modules/coveralls/bin/coveralls.js
